// <auto-generated />
using System;
using Dotnet_M1_A2.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet_M1_A2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240124130318_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dotnet_M1_A2.Models.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"), 1L, 1);

                    b.Property<string>("Nominee1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nominee2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nominee3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nominee4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionID");

                    b.ToTable("positionTbl");

                    b.HasData(
                        new
                        {
                            PositionID = 1,
                            Nominee1 = "John",
                            Nominee2 = "Jane",
                            Nominee3 = "Mike",
                            Nominee4 = "Sara",
                            PositionName = "President"
                        },
                        new
                        {
                            PositionID = 2,
                            Nominee1 = "Alex",
                            Nominee2 = "Emily",
                            Nominee3 = "Chris",
                            Nominee4 = "Lily",
                            PositionName = "Vice President"
                        },
                        new
                        {
                            PositionID = 3,
                            Nominee1 = "Yash",
                            Nominee2 = "Jill",
                            Nominee3 = "Daniel",
                            Nominee4 = "Peter",
                            PositionName = "Captain"
                        },
                        new
                        {
                            PositionID = 4,
                            Nominee1 = "Michale",
                            Nominee2 = "jack",
                            Nominee3 = "Deni",
                            Nominee4 = "Dory",
                            PositionName = "Secretary"
                        });
                });

            modelBuilder.Entity("Dotnet_M1_A2.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("studentTbl");
                });

            modelBuilder.Entity("Dotnet_M1_A2.Models.Vote", b =>
                {
                    b.Property<int>("VoteSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteSerialID"), 1L, 1);

                    b.Property<DateTime>("Date_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomineeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("VoteSerialID");

                    b.HasIndex("PositionID");

                    b.HasIndex("StudentID");

                    b.ToTable("voteTbl");
                });

            modelBuilder.Entity("Dotnet_M1_A2.Models.Vote", b =>
                {
                    b.HasOne("Dotnet_M1_A2.Models.Position", "positionTbl")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dotnet_M1_A2.Models.Student", "studentTbl")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("positionTbl");

                    b.Navigation("studentTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
